package movieReviewClassification;

import java.io.IOException;
import java.util.Scanner;
import java.io.Serializable;

/**
  Movie Review class
  @author williams
  @author bowers
 */

public class MovieReview implements Serializable {

    // Constructor
    public MovieReview() {
        id = 0;
        text = "";
        predicted = 0;
        real = 0;
    }


    /** @return ID field */
    public int getId() { return id; }
    /** @return text field */
    public String getText() { return text; }
    /** @return predicted polarity field */
    public int getPredictedPolarity() { return predicted; }
    /** @return ground truth "real" field */
    public int getRealPolarity() { return real; }

    /** @param i sets the ID field */
    public void setId(int i) { id = i; }
    /** @param t sets the text field */
    public void setText(String t) { text = t; }
    /** @param p sets the predicted polarity field */
    public void setPredictedPolarity(int p) { predicted = p; }
    /** @param r sets the ground truth "real" field */
    public void setRealPolarity(int r) { real = r; }

    // Variables
    // Used for organizing, removing, and searching MovieReview objects
    private int id;
    // Text taken from the movie review file
    private String text;
    // Review's polarity generated by the sentiment algorithm
    private int predicted;
    // Ground truth of the review's polarity, if it is avaliable.
    private int real;



}
